[GENERAL]
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"
KEEP_ALIVE = "-1m" # How long to keep Ollama models loaded into memory. (Instead of using -1 use "-1m")

[API_ENDPOINTS]
SEARXNG = "" # SearxNG API URL - http://localhost:32768


# Model priority for 'Speed' searches.
[[MODELS.SPEED]]
model_name = "gemma3:4b-it-qat"
provider = "ollama"
api_url = "https://..."
api_key = ""

[[MODELS.SPEED]]
model_name = "llama3.2:3b"
provider = "ollama"
api_url = "https://..."
api_key = ""


# Model priority for 'Quality' searches.
[[MODELS.QUALITY]]
model_name = "qwen3:30b-a3b-q8_0"
provider = "ollama"
api_url = "https://..."
api_key = ""

[[MODELS.QUALITY]]
model_name = "deepseek-r1:32b"
provider = "ollama"
api_url = "https://..."
api_key = ""


# Model priority for embedding.
[[MODELS.EMBEDDING]]
model_name = "snowflake-arctic-embed2:568m"
provider = "ollama"
api_url = "https://..."
api_key = ""

[[MODELS.EMBEDDING]]
model_name = "snowflake-arctic-embed:335mm"
provider = "ollama"
api_url = "https://..."
api_key = ""

[[MODELS.EMBEDDING]]
model_name = "nomic-embed-text:v1.5"
provider = "ollama"
api_url = "https://..."
api_key = ""
